# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42ced2eb746cd2f7e6d2b01d5f774a09b36c93ab0928afdb866fcdfed61a9a01978bb118fe0149fcac21b600274c4e148cf3c2aa5ce47131db4d9068d860fd56

test:
  secret_key_base: 30bbe6ced559f39ccad9b281c42405087a094a1bd35383341aa4b4021e95d3c77cb6d1c51e9fc17ea2160d2d8e3e29c2724a5a926637e4d0d5ef07f367a227da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
